name: Deploy BackEnd to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          port: 22

          script: |
            echo "Starting deployment..."

            # Navigate to backend folder
            cd /home/ubuntu/anaztexintlbackend

            echo "Pulling latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Stopping old PM2 process if exists..."
            pm2 delete anaztexintlbackend || true

            echo "Starting backend with PM2..."
            pm2 start index.js --name anaztexintlbackend

            echo "Saving PM2..."
            pm2 save

            echo "Deployment completed successfully."