name: Deploy BackEnd to EC2

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # fetch all history for the repo
          fetch-depth: 0

      # Step 2: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          port: 22
          script: |
            # Navigate to project directory
            cd /home/${{ secrets.EC2_USER }}/anaztexintlbackend || mkdir -p /home/${{ secrets.EC2_USER }}/anaztexintlbackend && cd /home/${{ secrets.EC2_USER }}/anaztexintlbackend

            # Configure Git to use GitHub Personal Access Token (for private repo)
            git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

            # Reset and pull latest code
            git reset --hard origin/main
            git pull origin main

            # Install/update dependencies
            npm install

            # Restart or start the app with PM2
            pm2 restart anaztexintlbackend || pm2 start index.js --name anaztexintlbackend

            # Save PM2 process list
            pm2 save